### ISSUE TITLE
Bug when using conda-lock within environment deployment

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-ram-condaenv#3]
There is currently [this issue in the conda github repo](https://github.com/conda/conda-lock/issues/487) related to a bug with `conda-lock` when a package in the environment yaml file contains a hash (`#`) in the package specification.

This happens to be the case for this repo's [`env.yml` file](https://github.com/ACCESS-NRI/access-ram-condaenv/blob/main/env.yml#L13) in the `mule` installation through `pip` (note the `#subdirectory=mule` at the end of the line).

This, as reported in the conda GitHub repo issue above, causes the current [`deployment action` to fail](https://github.com/ACCESS-NRI/access-ram-condaenv/actions/runs/10381568941/job/28743186886) with the same error.
I also tested the deployment when commenting the "hashy" line in the `env.yml` file, and in that case `conda-lock` runs without problems, meaning the hash (`#`) is effectively the problem here.

Currently, `mule` needs to be installed through `pip` as specified in this repo's `env.yml` (containing a hash (`#`) within the `pip` package installation line).

Is there any way to solve this for the time being? 
Do we have any alternatives to using `conda-lock`?

@CodeGat

**Comment by CodeGat** [comment]
Seems like this PR might be relevant: https://github.com/ACCESS-NRI/payu-condaenv/pull/37#issuecomment-2287665832 in which Jo and myself were talking about the `#subdirectory=mule` bit. @jo-basevi might be able to help as well.

**Comment by atteggiani** [comment]
In the PR you linked, only the `env-dev.yml` environment is deployed, so the [`deploy-dev.yml`](https://github.com/ACCESS-NRI/payu-condaenv/blob/34-add-mule-to-payu-dev/.github/workflows/deploy-dev.yml) is run for the action.
But in the `deploy-dev.yml` file there is no `conda-lock` run in the `Create Pack` step:

https://github.com/ACCESS-NRI/payu-condaenv/blob/485b4d9dd02a46c070a603b837c9b7880f214cf2/.github/workflows/deploy-dev.yml#L88-L90

whereas in the `deploy.yml` there is:

https://github.com/ACCESS-NRI/payu-condaenv/blob/485b4d9dd02a46c070a603b837c9b7880f214cf2/.github/workflows/deploy.yml#L46-L50

The `conda-lock` run is what causes issues.
Whenever the `env.yml` file is going to be depoyed, it might trigger this bug also in the `payu-condaenv` case.

**Comment by jo-basevi** [comment]
Yeah we are going to run into issues with payu-condaenv too once pip install `mule` is added to `env.yaml`.. I think `conda-lock` is not essential for the deployment as it was a reference of what dependencies were installed. I don't have any great ideas on alternatives. Could use `micromamba list` to obtain the micromamba dependencies and a `pip list` to get list of pip dependencies and adding those to a file.

**Comment by jo-basevi** [comment]
As we are using `conda-pack`, the environment is already fixed and the environment can be reproduced by downloading the packed environment file so maybe using `conda-lock` file is not as necessary?

**Comment by atteggiani** [comment]
> As we are using `conda-pack`, the environment is already fixed and the environment can be reproduced by downloading the packed environment file so maybe using `conda-lock` file is not as necessary?

The conda-lock is for "external usage" to be placed in the release files.
I commented it out for now so it won't be produced. 
I would say it's not a must-have, but definitely a good thing to have if the issue gets solved!

**Comment by atteggiani** [comment]
Fixed by replacing `mule` installation through `pip` with [`mule` from `coecms` conda channel](https://anaconda.org/coecms/mule)! 
Thank you @jo-basevi !

**Comment by CodeGat** [comment]
@atteggiani I think you meant @jo-basevi  :laughing:

**Comment by atteggiani** [comment]
Oopssss 🤣
