### ISSUE TITLE
Define deployment location for environment on Gadi

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-ram-condaenv#4]
We need to define the location (folder) on _Gadi_ where the `access-ram` conda environment files are going to be deployed. 

For now I set the deploymebt location (for testing) to `/g/data/tm70/access-ram-env_testing`. 

Once the decision has been made, the `ENVIRONMENT_DIR` var in the [Gadi Environment](https://github.com/ACCESS-NRI/access-ram-condaenv/settings/environments/3687957553/edit) needs to be changed to the chosen destination.
 

Are there any thoughts on the final destination?

**Comment by CodeGat** [comment]
Maybe under `/g/data/vk83/apps/`? Seems to be where we put other scripts like `om2-scripts` and `om3-scripts`. 
Would also allow for developer builds under `g/data/vk83/prerelease/apps` as well, in future.

**Comment by atteggiani** [comment]
I believe this was solved with the first release? @CodeGat
